#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm.hpp>
#include <gtx/string_cast.hpp>
#include <ext.hpp>
#include <vector>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>